#!/usr/bin/env python3
"""Download WordPress attachment URLs from migration_export/data/attachments.json."""

from __future__ import annotations

import argparse
import json
import mimetypes
import re
import urllib.error
import urllib.request
from pathlib import Path
from urllib.parse import urlparse


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9.]+", "-", value)
    return value.strip("-") or "download"


def filename_for(item: dict, content_type: str | None) -> str:
    url_path = Path(urlparse(item.get("attachment_url") or item.get("link") or "").path)
    name = url_path.name or item.get("slug") or item.get("post_id") or "download"
    name = slugify(name)
    if "." not in name and content_type:
        extension = mimetypes.guess_extension(content_type.split(";")[0].strip())
        if extension:
            name += extension
    return name


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--attachments",
        type=Path,
        default=Path("migration_export/data/attachments.json"),
        help="Path to attachments JSON generated by tools/export_wxr.py",
    )
    parser.add_argument("--out", type=Path, default=Path("migration_export/media"))
    parser.add_argument("--timeout", type=int, default=30)
    args = parser.parse_args()

    attachments = json.loads(args.attachments.read_text(encoding="utf-8"))
    args.out.mkdir(parents=True, exist_ok=True)
    report = []

    for item in attachments:
        url = item.get("attachment_url") or item.get("link")
        if not url:
            report.append({"post_id": item.get("post_id"), "status": "skipped", "reason": "missing URL"})
            continue

        request = urllib.request.Request(url, headers={"User-Agent": "VoAC migration media downloader"})
        try:
            with urllib.request.urlopen(request, timeout=args.timeout) as response:
                content_type = response.headers.get("content-type")
                filename = filename_for(item, content_type)
                target = args.out / filename
                suffix = 1
                while target.exists():
                    target = args.out / f"{Path(filename).stem}-{suffix}{Path(filename).suffix}"
                    suffix += 1
                target.write_bytes(response.read())
                report.append(
                    {
                        "post_id": item.get("post_id"),
                        "url": url,
                        "status": "downloaded",
                        "path": str(target),
                        "content_type": content_type,
                    }
                )
                print(f"downloaded {url} -> {target}")
        except (urllib.error.URLError, TimeoutError) as exc:
            report.append({"post_id": item.get("post_id"), "url": url, "status": "failed", "error": str(exc)})
            print(f"failed {url}: {exc}")

    (args.out / "download-report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
